### ISSUE TITLE
Add the ability to do Integration tests in projects easily

### ISSUE THREAD

**Issue by Harlekuin** [Harlekuin/SimQLe#1]

**Comment by ZackBotkin** [comment]
I left a comment on the pull request I left open, but I suggest "behave" framework. I wrote a very basic test, and I'm planning on adding more. You can check out the branch "hack-hack" on my fork of your code to see this. Once I'm happy with the amount of test coverage, I'll merge "hack-hack" back into "hack", and then pull request "hack" onto your branch "dev"

**Comment by Harlekuin** [comment]
Ah, so this one was a fairly vague enhancement, that means more that projects that utilise simqle in them can create integration tests really easily. It definitely needs more canvassing - I had a few ideas but nothing down on paper yet

**Comment by Harlekuin** [comment]
This Issue has turned into a whole new project... https://github.com/Harlekuin/sqema, so I'll close it here
