### ISSUE TITLE
Add a default parameter option to the .connections.yaml file

### ISSUE THREAD

**Issue by Harlekuin** [Harlekuin/SimQLe#18]
This way SimQLe can know which connection to use when no con_name is specified in either recordset() or execute_sql(), and save the user time, especially when dealing with only one connection in a project.

**Comment by ZackBotkin** [comment]
Hey. so it looks like you've got a number of issues that people can work on.  I've forked your code and am using this branch

https://github.com/ZackBotkin/SimQLe/tree/hack

to kind of play around/hack. One thing I noticed.. you don't really seem to use classes or any sort of object oriented style. I find it really helps the maintainability of the project. You can check out my branch to see what I am doing, and I'll send you a pull request when done.

**Comment by ZackBotkin** [comment]
Once I kind of get my feet wet with the code/idea, I could take any of these issues.

**Comment by Harlekuin** [comment]
Interesting - if you think it would be easier to maintain then I am all for it! Would these be singleton classes mainly? I'm not entirely sure how you intend to do this so I'm looking forward to seeing your PR.

Regarding this particular issue - it should be a very easy change to simply add a default: true option to the connections file that is selected when no con_name is defined when calling recordset() or execute_sql() - happy for anyone to submit a pr :)

**Comment by Harlekuin** [comment]
closed in #45 and released in #46
