### ISSUE TITLE
Upgrade the integration tests to Behave

### ISSUE THREAD

**Issue by Harlekuin** [Harlekuin/SimQLe#36]
https://github.com/behave/behave

**Comment by ZackBotkin** [comment]
this is basically the hack-hack branch right? I'm gonna try and finish up the behave integration tests today for PostgreSQL, after I go through and pull in the latest changes

**Comment by Harlekuin** [comment]
closed in #38

**Comment by ZackBotkin** [comment]
Looks good, well done on the test integration. I'm spending the weekend w
my fiance plus parents. Hope to have some time to work on it this week.
